global using Microsoft.Azure.Cosmos;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Polly;
global using System.Net;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.Extensions.Diagnostics.HealthChecks;